version: "3"
services:
  database:
    image: postgres:14.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nest_project
    ports:
      - "5432:5432"
    volumes: 
      - ./src/database/sql/todo.sql:/docker-entrypoint-initdb.d/todo.sql     
  api: 
    build: .
    ports: 
      - "3000:3000"
      - "9230:9230"
    depends_on:
      - database
    volumes:
      - $PWD:/app
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ssh:/root/.ssh
    # store all credentials in the same place 
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: nest_project
    links:
      - database
  